apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    from locust import HttpUser, task, between, tag


    class LoadSimulator(HttpUser):
        wait_time = between(0.5, 2)
        
        @task
        @tag('checkDevices')
        def do_device_check(self):
            self.client.get(f"/api/devices/", name="/devices/")