#
#
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-config
  namespace: default
data:
  HIKARI_POOL_SIZE: "10"
  HIKARI_MAX_LIFETIME: "1800000"
  HIKARI_INIT_FAIL_TIMEOUT: "90000"
  HIKARI_VALIDATION_TIMEOUT: "60000"
  HIKARI_LOG_LEVEL: DEBUG
  HIKARI_CONFIG_LOG_LEVEL: DEBUG
  YB_DB_DATABASE: yugabyte
  YB_DB_SCHEMA: public
  YB_DB_ISOLATION: TRANSACTION_READ_COMMITTED
  YB_DB_SERVER_NAME: "10.207.0.79"
  YB_DB_PORT_NUMBER: "5433"
  YB_DB_ADDITIONAL_ENDPOINTS: "10.207.0.80,10.200.0.70,10.200.0.61"
  YB_DB_TOPOLOGY_KEYS: "gcp.us-east4.us-east4-a,gcp.us-east4.us-east4-b"
  YB_DB_SOCKET_TIMEOUT_SECONDS: "8"
  YB_DB_PREPARE_THRESHOLD: "1"
  YB_DB_OPTIONS: "-c statement_timeout=30s"
  HIBERNATE_DDL_MODE: none
  HIBERNATE_BATCH_SIZE: "30"
  HIBERNATE_CONNECTION_HANDLING_MODE: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
  HIBERNATE_GENERATE_STATISTICS: "false"
  HIBERNATE_USER_SQL_COMMENTS: "false"
  HIBERNATE_DEBUG_SQL: INFO
  HIBERNATE_DEBUG_SQL_PARAMS: INFO